services:
  dashboard:
    build: .
    container_name: dash
    restart: unless-stopped
    pull_policy: build
    env_file:
      - stack.env
    labels:
      - 'traefik.http.routers.dash.rule=Host(`gaia.mrcube.dev`)'
      - 'traefik.http.services.dash.loadbalancer.server.port=3000'
